describe('Registration Form - Negative Scenario', () => {
    it('Shows error when Last Name is missing', () => {
        cy.visit('/')
        cy.title().should('exist')
        cy.get('input[name="firstName"]').type('John')
        cy.get('input[name="email"]').type('john@example.com')
        cy.get('input[name="phone"]').type('+1234567890')
        cy.get('select[name="country"]').select('USA')
        cy.get('select[name="state"]').select('California')
        cy.get('select[name="city"]').select('Los Angeles')
        cy.get('input[name="gender"][value="Male"]').check()
        cy.get('input[name="password"]').type('Password123!')
        cy.get('input[name="confirmPassword"]').type('Password123!')
        cy.get('input[name="terms"]').check()
        cy.get('button[type="submit"]').click()
        cy.contains('Last name is required').should('be.visible')
        cy.get('input[name="lastName"]').should('have.class', 'error')
        cy.screenshot('error-state')
    })
})

describe('Registration Form - Positive Scenario', () => {
    it('Submits successfully with valid data', () => {
        cy.visit('/')
        cy.get('input[name="firstName"]').type('Jane')
        cy.get('input[name="lastName"]').type('Doe')
        cy.get('input[name="email"]').type('jane.doe@example.com')
        cy.get('input[name="phone"]').type('+19876543210')
        cy.get('select[name="country"]').select('Canada')
        cy.get('select[name="state"]').select('Ontario')
        cy.get('select[name="city"]').select('Toronto')
        cy.get('input[name="gender"][value="Female"]').check()
        cy.get('input[name="password"]').type('StrongPass1!')
        cy.get('input[name="confirmPassword"]').type('StrongPass1!')
        cy.get('input[name="terms"]').check()
        cy.on('window:alert', (txt) => {
            expect(txt).to.contains('Registration Successful!')
        })
        cy.get('button[type="submit"]').click()
        cy.screenshot('success-state')
    })
})

describe('Registration Form - Logic Validation', () => {
    it('Validates dropdown dependency, password strength, and mismatch correctly', () => {
        cy.visit('/')
        cy.get('select[name="country"]').select('USA')
        cy.get('select[name="state"]').select('Texas')
        cy.get('select[name="city"]').select('Houston')
        cy.get('input[name="password"]').type('weak')
        cy.contains('Strength: Weak').should('be.visible')
        cy.get('input[name="password"]').clear().type('Medium1')
        cy.contains('Strength: Medium').should('be.visible')
        cy.get('input[name="password"]').clear().type('StrongPass123!')
        cy.contains('Strength: Strong').should('be.visible')
        cy.get('input[name="confirmPassword"]').type('Different')
        cy.get('button[type="submit"]').click()
        cy.contains('Passwords do not match').should('be.visible')
        cy.get('input[name="confirmPassword"]').clear().type('StrongPass123!')
        cy.get('button[type="submit"]').click()
        cy.contains('Passwords do not match').should('not.exist')
        cy.screenshot('Logic-Validation')
    })
})
